### ISSUE TITLE
Getting maintainer permission

### ISSUE THREAD

**Issue by guyluz11** [jonathantribouharet/flutter_cast#53]
Hello @johnvuko 

I would like to keep this package alive and get permission to accept pr and upload a new version of the package.

As you can see by the open pr I made a lot of changes that could benefit everyone with a lot of new features.
I would love to help and continue to this awesome package.

In case you prefer not to touch the package another option is to upload a copy of the package from my fork but the original package is preferred.

Thanks and waiting for your response

**Comment by guyluz11** [comment]
If anybody is looking for dart native support and more features you can use my fork.

```
 cast: 
    git: 
      url: "https://github.com/guyluz11/flutter_cast.git"
      ref: "multicast_version"

```

To inspect some of the new features check pr #51
